/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * Copyright 2012-2021 the original author or authors.
 */
package org.assertj.core.api.map;

import static org.assertj.core.api.BDDAssertions.then;
import static org.assertj.core.util.AssertionsUtil.expectAssertionError;
import static org.assertj.core.error.ShouldContainKeys.shouldContainKeys;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.util.Arrays.array;
import static org.mockito.Mockito.verify;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.assertj.core.api.Condition;
import org.assertj.core.api.MapAssert;
import org.assertj.core.api.MapAssertBaseTest;
import org.junit.jupiter.api.Test;


/**
 * Tests for <code>{@link MapAssert#containsKey(Object)}</code>.
 *
 * @author Nicolas François
 */
class MapAssert_containsKey_Test extends MapAssertBaseTest {

  @Override
  protected MapAssert<Object, Object> invoke_api_method() {
    return assertions.containsKey("key1");
  }

  @Override
  protected void verify_internal_effects() {
    verify(maps).assertContainsKeys(getInfo(assertions), getActual(assertions), array("key1"));
  }
  
  @Test
  protected void should_fail_when_asserting_for_null_on_map_that_does_not_contian_null() {
    Set<String> helper = new HashSet<>();
    helper.add(null);
    
    // GIVEN
    Map<String, String> actual = Map.of("whatever", "don't care");
    // WHEN
    AssertionError assertionError = expectAssertionError(() -> assertThat(actual).containsKey(null));
    // THEN
    /* This is not ideal. It feels to me like this should be a call to 
     * ShouldContainKey.shouldContainKey(). However, internally the assertion
     * error is generated by ShouldContainKeys -- and that has a different 
     * error message.
     */
    then(assertionError).hasMessage(shouldContainKeys(actual, helper).create());
  }
}
