[[assertj-joda-time-release-notes]]
=== Release Notes

Latest release notes:

- link:#assertj-joda-time-2-2-0-release-notes[AssertJ Joda Time 2.2.0]
- link:#assertj-joda-time-2-1-0-release-notes[AssertJ Joda Time 2.1.0]
- link:#assertj-joda-time-2-0-0-release-notes[AssertJ Joda Time 2.0.0]

The javadoc for this release can be found here: https://www.javadoc.io/doc/org.assertj/assertj-joda-time/2.2.0/index.html

[[assertj-joda-time-2-2-0-release-notes]]
==== AssertJ Joda Time 2.2.0

Release date: 2018-06-15

[[assertj-joda-time-2.2.0-contributors]]
[.release-note-category]#icon:user[] Contributors#

Thanks to Eugene Strepetov for his contribution.

[[assertj-joda-time-2.2.0-new-features]]
[.release-note-category]#icon:plus-circle[] New features#

Add `LocalDate` assertions providing the following ones (Eugene Strepetov): 

- `hasYear`: Verifies that the year of the actual LocalDate is equal to the given year.
- `hasMonthOfYear`: Verifies that the month of the actual LocalDate is equal to the given month
- `hasDayOfMonth`: Verifies that the day of month of the actual LocalDate is equal to the given day
- `isBefore`: Verifies that the actual LocalDate is strictly before the given one.
- `isBeforeOrEqualTo`: Verifies that the actual LocalDate is before or equals to the given one.
- `isEqualTo`: Same assertion as `AbstractAssert.isEqualTo(Object...)` but to be used with `LocalDate` String representation.
- `isAfter`: Verifies that the actual LocalDate is strictly after the given one.
- `isAfterOrEqualTo`: Verifies that the actual LocalDate is after or equals to the given one.
- `isIn`: Same assertion as `AbstractAssert.isIn(Object...)` but to be used with `LocalDate` String representation.
- `isNotIn`: Same assertion as `AbstractAssert.isNotIn(Object...)` but to be used with `LocalDate` String representation.

The assertions taking `String` parameter(s) can be used with `LocalDate` String representation: `yyyy-MM-dd`.

Examples:
[source,java,indent=0]
----
LocalDate localDate = new LocalDate(2000, 1, 1);

assertThat(localDate).hasYear(2000)
                     .hasMonthOfYear(1)
                     .hasDayOfMonth(1)
                     .isBefore(new LocalDate(2000, 1, 2))
                     .isBefore("2000-01-02")
                     .isBeforeOrEqualTo(new LocalDate(2000, 1, 1))
                     .isBeforeOrEqualTo("2000-01-01")
                     .isBeforeOrEqualTo(new LocalDate(2000, 1, 2))
                     .isBeforeOrEqualTo("2000-01-02")
                     .isEqualTo(new LocalDate(2000, 1, 1))
                     .isEqualTo("2000-01-01")
                     .isAfterOrEqualTo(new LocalDate(2000, 1, 1))
                     .isAfterOrEqualTo("2000-01-01")
                     .isAfterOrEqualTo(new LocalDate(1999, 12, 31))
                     .isAfterOrEqualTo("1999-12-31")
                     .isAfter(new LocalDate(1999, 12, 31))
                     .isAfter("1999-12-31")
                     .isNotEqualTo("2000-01-15")
                     .isNotEqualTo(new LocalDate(2000, 1, 15))
                     .isIn(new LocalDate(1999, 12, 31), new LocalDate(2000, 1, 1))
                     .isIn("1999-12-31", "2000-01-01")
                     .isNotIn(new LocalDate(1999, 12, 31), new LocalDate(2000, 1, 2))
                     .isNotIn("1999-12-31", "2000-01-02");
----


[[assertj-joda-time-2-1-0-release-notes]]
==== AssertJ Joda Time 2.1.0

Release date: 2018-05-27

[[assertj-joda-time-2.1.0-contributors]]
[.release-note-category]#icon:user[] Contributors#

Thanks to John Killmer for his contribution.

[[assertj-joda-time-2.1.0-new-features]]
[.release-note-category]#icon:plus-circle[] New features#

Add `LocalDateTime` assertions providing the following ones (John Killmer): 

- `hasYear`: Verifies that the year of the actual LocalDateTime is equal to the given year.
- `hasMonthOfYear`: Verifies that the month of the actual LocalDateTime is equal to the given month
- `hasDayOfMonth`: Verifies that the day of month of the actual LocalDateTime is equal to the given day of month
- `hasHourOfDay`: Verifies that the hour of the actual DateTime is equal to the given hour
- `hasMinuteOfHour`: Verifies that the minute of the actual LocalDateTime is equal to the given minute
- `hasSecondOfMinute`: Verifies that the seconds of the actual LocalDateTime is equal to the given seconds
- `hasMillisOfSecond`: Verifies that the milliseconds of the actual LocalDateTime is equal to the given milliseconds

Examples:
[source,java,indent=0]
----
DateTime dateTime = new DateTime(1999, 12, 31, 23, 59, 59, 999, DateTimeZone.UTC);

assertThat(dateTime).hasYear(1999)                                                
                    .hasMonthOfYear(12)                                           
                    .hasDayOfMonth(31)                                            
                    .hasHourOfDay(23)                                             
                    .hasMinuteOfHour(59)                                          
                    .hasSecondOfMinute(59)                                        
                    .hasMillisOfSecond(999);
----

[[assertj-joda-time-2-0-0-release-notes]]
==== AssertJ Joda Time 2.0.0

Release date: 2016-04-10

[[assertj-joda-time-2.0.0-contributors]]
[.release-note-category]#icon:user[] Contributors#

Thanks to Pascal Schumacher and David Simmons for their contributions.

[[assertj-joda-time-2-0-0-breaking-changes]]
[.release-note-category]#icon:exclamation-triangle[] Breaking changes#

AssertJ Joda Time 2.0.0 requires Java 8 as it relies on AssertJ Core 3.x, use 1.1.0 version if you are still using Java 7.

[[assertj-joda-time-2-0-0-improvements]]
[.release-note-category]#icon:arrow-circle-up[] Improvements#

* DateTime assertion : better handling of null in assertions. (David Simmons)
* To be OS agnostic, replace `\n` with `%n` in error messages. (Pascal Schumacher)
* Better spacing in Javadoc code examples. (Pascal Schumacher)



    
    
    
