[[assertj-guava-release-notes]]
=== Release Notes

NOTE: AssertJ Guava main documentation is still in http://joel-costigliola.github.io/assertj/assertj-guava.html until it is moved to this website. +
The new release notes though will be published here.

Latest release notes:

- link:#assertj-guava-3-24-0-release-notes[AssertJ Guava 3.24.0]
- link:#assertj-guava-3-5-0-release-notes[AssertJ Guava 3.5.0]
- link:#assertj-guava-3-4-0-release-notes[AssertJ Guava 3.4.0]
- link:#assertj-guava-3-3-0-release-notes[AssertJ Guava 3.3.0]
- Older release notes are in the http://joel-costigliola.github.io/assertj/assertj-guava.html#latest-release[old site].

[[assertj-guava-3-24-0-release-notes]]
==== AssertJ Guava 3.24.0

Release date : 2023-01-06

[[assertj-guava-3.24.0-binary-compatibility]]
[.release-note-category]#icon:cogs[] Binary compatibility#

The release [green]#is binary compatible# with the previous minor version.

[[assertj-guava-3.5.0-improvements]]
[.release-note-category]#icon:arrow-circle-up[] Improvements#
* AssertJ Guava is now part of the AssertJ multimodule and follows the same versioning.

[[assertj-guava-3-5-0-release-notes]]
==== AssertJ Guava 3.5.0

Release date : 2022-06-11

[[assertj-guava-3.5.0-contributors]]
[.release-note-category]#icon:user[] Contributors#

Thanks to all the contributors of this release:
Erhard Pointl,
Stefano Cordio,
BJ Hargrave icon:user-plus[title=New contributor],
sullis icon:user-plus[title=New contributor].

[[assertj-guava-3.5.0-binary-compatibility]]
[.release-note-category]#icon:cogs[] Binary compatibility#

The release [green]#is binary compatible# with the previous minor version.

[[assertj-guava-3.5.0-improvements]]
[.release-note-category]#icon:arrow-circle-up[] Improvements#

* Remove <> from error messages (Erhard Pointl)
* Internal: Add binary compatibility check of `main` against the latest release (Stefano Cordio)
* Internal: Add binary compatibility checks for pull requests (Stefano Cordio)
* Internal: Add Code of Conduct (Stefano Cordio)
* Internal: Add CodeQL workflow (Stefano Cordio)
* Internal: Add Dependabot (sullis)
* Internal: Add release workflow (Stefano Cordio)
* Internal: Bump actions/cache from v1 to v2
* Internal: Bump actions/checkout from 2 to 3
* Internal: Bump actions/setup-java from 1 to 3
* Internal: Bump actions/upload-artifact from 2 to 3
* Internal: Bump assertj-core from 3.15.0 to 3.23.1 (sullis, Erhard Pointl, Stefano Cordio)
* Internal: Bump assertj-parent-pom from 2.2.6 to 2.2.17
* Internal: Bump github/codeql-action from 1 to 2
* Internal: Bump guava from 29.0-jre to 31.1-jre
* Internal: Bump Maven version from 3.6.3 to 3.8.5 (Erhard Pointl, Stefano Cordio)
* Internal: Bump maven-bundle-plugin from 3.0.1 to 5.1.4
* Internal: Convert JUnit 4 tests to JUnit 5 (Stefano Cordio)
* Internal: Move `RangeSet` assertions to the api package (Stefano Cordio)
* Internal: Simplify maven-bundle-plugin configuration (Stefano Cordio)
* Internal: Switch to the official Maven Wrapper by Apache (Stefano Cordio)
* Internal: Update license headers (Erhard Pointl, Stefano Cordio)
* Internal: Use `bnd-maven-plugin` instead of `maven-bundle-plugin` (BJ Hargrave)

[[assertj-guava-3.5.0-fixed]]
[.release-note-category]#icon:wrench[] Fixed#

* Remove the usage of `assertj-core` internal API to fix the compatibility with OSGi (Stefano Cordio)

[[assertj-guava-3-4-0-release-notes]]
==== AssertJ Guava 3.4.0

Release date : 2020-04-24

[[assertj-guava-3.4.0-contributors]]
[.release-note-category]#icon:user[] Contributors#

Thanks to Ilya Koshaleu for its contribution!

[[assertj-guava-3.4.0-new-features]]
[.release-note-category]#icon:plus-circle[] New features#

Add `RangeSet` assertions (Ilya Koshaleu):

- `contains(T... ranges)`: Verifies that the given `RangeSet` contains the given ranges.
- `containsAll(Iterable<T> ranges)`: Verifies that the given `RangeSet` contains all the given ranges.
- `containsAnyOf(T... ranges)`: Verifies that the given `RangeSet` contains at least one of the given ranges.
- `containsAnyRangesOf(Iterable<T> ranges)`: Verifies that the given `RangeSet` contains at least one of the given ranges.
- `doesNotContain(T... ranges)`: Verifies that the given `RangeSet` does not contain any of the given ranges.
- `doesNotContainAll(Iterable<T> ranges)`: Verifies that the given `RangeSet` does not contain any of the given ranges.
- `doesNotEnclose(Range<T>... ranges)`: Verifies that the given `RangeSet` does not enclose the given ranges.
- `doesNotEncloseAnyRangesOf(RangeSet<T> rangeSet)`: Verifies that the given `RangeSet` does not enclose any range from the given range set.
- `doesNotEncloseAnyRangesOf(Iterable<Range<T>> ranges)`: Verifies that the given `RangeSet` does not enclose any of the given ranges.
- `doesNotIntersect(Range<T>... ranges)`: Verifies that the given `RangeSet` does not intersect the given ranges.
- `doesNotIntersectAnyRangeFrom(RangeSet<T> rangeSet)`: Verifies that the given `RangeSet` does not intersect ranges from the given range set.
- `doesNotIntersectAnyRangeFrom(Iterable<Range<T>> ranges)`: Verifies that the given `RangeSet` does not intersect all the given ranges.
- `encloses(Range<T>... ranges)`: Verifies that the given `RangeSet` encloses the given ranges.
- `enclosesAll(RangeSet<T> rangeSet)`: Verifies that the given `RangeSet` encloses all ranges from the given range set.
- `enclosesAll(Iterable<Range<T>> ranges)`: Verifies that the given `RangeSet` encloses all the given ranges.
- `enclosesAnyOf(Range<T>... ranges)`: Verifies that the given `RangeSet` encloses at least one of the given ranges.
- `enclosesAnyRangesOf(RangeSet<T> rangeSet)`: Verifies that the given `RangeSet` encloses at least one range from the given range set.
- `enclosesAnyRangesOf(Iterable<Range<T>> ranges)`: Verifies that the given `RangeSet` encloses at least one range of the given ranges.
- `hasSize(int size)`: Verifies that the given `RangeSet` has the specific size of disconnected Range elements.
- `intersects(Range<T>... ranges)`: Verifies that the given `RangeSet` intersects all the given ranges.
- `intersectsAll(RangeSet<T> rangeSet)`: Verifies that the given `RangeSet` intersects all the given range set.
- `intersectsAll(Iterable<Range<T>> ranges)`: Verifies that the given `RangeSet` intersects all the given ranges.
- `intersectsAnyOf(Range<T>... ranges)`: Verifies that the given `RangeSet` intersects at least one of the given ranges.
- `intersectsAnyRangesOf(RangeSet<T> rangeSet)`: Verifies that the given `RangeSet` intersects at least one range of the given range set.
- `intersectsAnyRangesOf(Iterable<Range<T>> ranges)`: Verifies that the given `RangeSet` intersects at least one of the given ranges.
- `isEmpty()`: Verifies that the actual RangeSet is empty.
- `isNotEmpty()`: Verifies that the actual RangeSet is not empty.
- `isNullOrEmpty()`: Verifies that the actual RangeSet is null or empty.

[[assertj-guava-3.4.0-improvements]]
[.release-note-category]#icon:arrow-circle-up[] Improvements#

- Javadoc uses AssertJ site beautiful theme :)
- Uses to assertj-core version 3.15.0.
- Uses to guava version 29.0-jre.
- Internal: setup github actions CI build and sonar reporting.

[[assertj-guava-3-3-0-release-notes]]
==== AssertJ Guava 3.3.0

Release date : 2019-11-09

[[assertj-guava-3.3.0-contributors]]
[.release-note-category]#icon:user[] Contributors#

Thanks to chrisly42 and Stefano Cordio for their contributions!

[[assertj-guava-3.3.0-new-features]]
[.release-note-category]#icon:plus-circle[] New features#

- Add link:#assertj-guava-3.3.0-InstanceOfAssertFactories[`InstanceOfAssertFactories`] to chain specific type assertions. (Stefano Cordio)

[[assertj-guava-3.3.0-improvements]]
[.release-note-category]#icon:arrow-circle-up[] Improvements#

- AssertJ's javadoc are now searchable.
- Use beautiful AssertJ's site code style for javadoc :)
- Migrate to JUnit 5 and assertj-core version 3.14.0.

[[assertj-guava-3.3.0-fixed]]
[.release-note-category]#icon:wrench[] Fixed#

- Fix for `OptionalAssert.contains()` that was not working for primitive arrays. (chrisly42)

[[assertj-guava-3.3.0-deprecated]]
[.release-note-category]#icon:ban[] Deprecated#

- Deprecate `org.assertj.guava.data.MapEntry` for `org.assertj.core.data.MapEntry`

[[assertj-guava-3.3.0-InstanceOfAssertFactories]]
[.release-note-item]#Add `InstanceOfAssertFactories` to allow chain specific type assertions#

Add factories for `ByteSource`, `Multimap`, `Multiset`, `Optional` (guava) and `Table` to allow to chain specific type assertions from a value initially declared as a less specific type.

Let's start with the problem `asInstanceOf` is solving: in the following example we would like to call `Table` assertions but this is not possible since `value` is declared as an `Object` thus only `Object` assertions are accessible.
[source,java,indent=0]
----
// Given a Table declared as an Object
Object actual = HashBasedTable.<Integer, Integer, String> create();

// We would like to call Table assertions but this is not possible since value is declared as an Object
assertThat(actual).isEmpty(); // this does not compile !
----

Thanks to `asInstanceOf` we can now tell AssertJ to consider `value` as a `Table` in order to call `Table` assertions. +
To do so we need to pass an `InstanceOfAssertFactory` that can build a `TableAssert`, fortunately you don't have to write it, it is already available in `InstanceOfAssertFactories`!

[source,java,indent=0]
----
// Given a Table declared as an Object
Object actual = HashBasedTable.<Integer, Integer, String> create();

// With asInstanceOf, we switch to specific Table assertion by specifying the InstanceOfAssertFactory for Table
assertThat(value).asInstanceOf(InstanceOfAssertFactories.TABLE)
                 .isEmpty();
----

AssertJ verifies that the actual value is compatible with the assertions `InstanceOfAssertFactory` is going to give access to.

`InstanceOfAssertFactories` provides static factories for all types AssertJ provides assertions for, additional factories can be created with custom `InstanceOfAssertFactory` instances.

