[[assertj-samples]]
= AssertJ Sample Projects

The {assertj-examples-repo}[assertions-examples] repository hosts executable AssertJ assertions examples that you can run as
JUnit tests. Please have a look at assertions {assertj-examples-repo}/tree/main/assertions-examples/src/test/java/org/assertj/examples[examples sources].

The `main` branch contains examples with the latest released version of AssertJ modules for Java 8, similarly the `java-7` branch
contains examples of AssertJ modules for Java 7. You should be able to build those two branches with `mvn clean install` command.

In your IDE, add `src/test/generated-assertions` to the project java test sources otherwise you will have errors/missing classes. This is the folder where custom assertions classes are generated by default by the maven assertions generator plugin. Note that Intellij Idea wrongly adds `src/test/generated-assertions` to the production sources when it should be added the test sources, you will have to fix that in your module/project settings.

Building the `with-latest-snapshot-versions` branch is a bit more complicated :

* you need to build the needed SNAPSHOT dependencies before - most probably assertj-core and maybe other modules.
* run `mvn clean install` in assertj-examples/assertions-examples.
* In your IDE, add `src/test/generated-assertions` to the project java sources if you IDE shows errors/missing classes.
