[[assertj-migration]]
=== Migrating assertions

This page will help you converting your existing JUnit assertions to AssertJ ones. Note that both types of assertions can coexist, you don't have to migrate all at once.

The idea is to convert code like :

[source,java,indent=0]
----
assertEquals(expected, actual);
----

to:

[source,java,indent=0]
----
assertThat(actual).isEqualTo(expected);
----

There are several ways to perform the conversion :

* Automatically using the provided link:#assertj-migration-using-scripts[migration scripts].
* Manually using the regexes described in this link:#assertj-migration-using-regexes[section].
* With IntelliJ IDEA, using these plugins:
** https://plugins.jetbrains.com/plugin/10345-assertions2assertj[Assertions2Assertj] plugin.
** https://plugins.jetbrains.com/plugin/12195-concise-assertj-optimizing-nitpicker-cajon-[Concise AssertJ Optimizing Nitpicker (Cajon)] plugin.
* With IntelliJ IDEA, using the Structural Search and Replace (SSR) feature.

The preferred way is using the scripts as it is quicker and covers more assertions that the other ones.

[[assertj-migration-using-scripts]]
==== Assertions migration scripts

It is as simple as running one of the following script depending on which test framework you are using:

* {current-branch}/assertj-core/src/main/scripts/convert-junit-assertions-to-assertj.sh[JUnit 3/4 to AssertJ migration script]
* {current-branch}/assertj-core/src/main/scripts/convert-junit5-assertions-to-assertj.sh[JUnit 5 to AssertJ migration script]
* {current-branch}/assertj-core/src/main/scripts/convert-testng-assertions-to-assertj.sh[TestNG to AssertJ migration script]

Each shell scripts is based on the sed stream editor and regexps. It *recursively* looks at all `*Test.java` files and
performs search and replace to convert assertions to AssertJ ones.

The script handles the cases where you use an assertion description, for example:

[source,java,indent=0]
----
assertEquals("test context", "a", "a");
----
will be replaced by:
[source,java,indent=0]
----
assertThat("a").as("test context").isEqualTo("a");
----


Note that the script does a best effort and some assertions might not be converted if formatted on multiple lines. Anyway the script usually migrates the vast majority of assertions.

The script works on windows within a bash console like git bash (tested a long time ago) or cygwin (not tested).

===== Usage

Execute the script in the base directory containing the test files:

[source,bash,indent=0]
----
cd ./src/test/java
./convert-junit-assertions-to-assertj.sh
----

If the `*Test.java` file pattern does not suit you, just specify another as an argument:
[source,bash,indent=0]
----
# enclose your pattern with double quotes "" to avoid it to be expanded by your shell prematurely
./convert-junit-assertions-to-assertj.sh "*IT.java"
----

After executing it, you will need to :

* Optimize imports with your IDE to remove unused imports.
* If you were using `assertEquals` with a delta to compare numbers, you will need to statically import `org.assertj.core.api.Assertions.within` which is how you express deltas in AssertJ (see the {assertj-examples-repo}/blob/main/assertions-examples/src/test/java/org/assertj/examples/NumberAssertionsExamples.java[number_assertions_with_offset_examples()] test at the end of `NumberAssertionsExamples`).

===== Script output

[source, text]
----
Converting JUnit assertions to AssertJ assertions on files matching pattern : *Test.java

 1 - Replacing : assertEquals(0, myList.size()) ............... by : assertThat(myList).isEmpty()
 2 - Replacing : assertEquals(expectedSize, myList.size()) .... by : assertThat(myList).hasSize(expectedSize)
 3 - Replacing : assertEquals(expectedDouble, actual, delta) .. by : assertThat(actual).isCloseTo(expectedDouble, within(delta))
 4 - Replacing : assertEquals(expected, actual) ............... by : assertThat(actual).isEqualTo(expected)
 5 - Replacing : assertArrayEquals(expectedArray, actual) ..... by : assertThat(actual).isEqualTo(expectedArray)
 6 - Replacing : assertNull(actual) ........................... by : assertThat(actual).isNull()
 7 - Replacing : assertNotNull(actual) ........................ by : assertThat(actual).isNotNull()
 8 - Replacing : assertTrue(logicalCondition) ................. by : assertThat(logicalCondition).isTrue()
 9 - Replacing : assertFalse(logicalCondition) ................ by : assertThat(logicalCondition).isFalse()
10 - Replacing : assertSame(expected, actual) ................. by : assertThat(actual).isSameAs(expected)
11 - Replacing : assertNotSame(expected, actual) .............. by : assertThat(actual).isNotSameAs(expected)

Replacing JUnit static imports by AssertJ ones, at this point you will probably need to :
12 --- optimize imports with your IDE to remove unused imports
12 --- add "import static org.assertj.core.api.Assertions.within;" if you were using JUnit number assertions with deltas
----

[[assertj-migration-using-regexes]]
==== Assertions migration regexes

Here's a list of find/replace expressions to change JUnit assertions into AssertJ assertions (don't forget to check the regex mode in your editor replace window).

This regexes described in this section are specific to JUnit 4 but you can easily adapt them for JUnit 5 or TestNG.

The order of find/replace is important to benefit from the most relevant AssertJ assertions. For example you should convert `assertEquals(0, myList.size())` to `assertThat(myList).isEmpty()` instead of `assertThat(myList.size()).isEqualTo(0)`.


===== Converting `assertEquals(0, myList.size())` to `assertThat(myList).isEmpty()`

Find/replace regex:

[source,bash,indent=0]
----
assertEquals\(0,(.*).size\(\)\); -> assertThat(\1).isEmpty();
----

It's better to run this before the `assertEquals` -> `isEqualTo` conversion to avoid ending with `assertThat(myList.size()).isEqualTo(0)`.

===== Converting `assertEquals(size, myList.size())` to `assertThat(myList).hasSize(size)`

Find/replace regex:

[source,bash,indent=0]
----
assertEquals\((.*),(.*).size\(\)\); -> assertThat(\2).hasSize(\1);
----

It's better to run this before the `assertEquals` -> `isEqualTo` conversion to avoid ending with `assertThat(myList.size()).isEqualTo(expectedSize)`.

===== Converting `assertEquals(expected, actual)` to `assertThat(actual).isEqualTo(expected)`

Find/replace regex:

[source,bash,indent=0]
----
assertEquals\((.*),(.*)\); -> assertThat(\2).isEqualTo(\1);
----

===== Converting `assertNull(objectUnderTest)` to `assertThat(objectUnderTest).isNull()`

Find/replace regex:

[source,bash,indent=0]
----
assertNull\((.*)\); -> assertThat(\1).isNull();
----

===== Converting `assertNotNull(objectUnderTest)` to `assertThat(objectUnderTest).isNotNull()`

Find/replace regex:

[source,bash,indent=0]
----
assertNotNull\((.*)\); -> assertThat(\1).isNotNull();
----

===== Converting `assertFalse(logicalCondition)` to `assertThat(logicalCondition).isFalse()`

Find/replace regex:

[source,bash,indent=0]
----
assertFalse\((.*)\); -> assertThat(\1).isFalse();
----
