name: CI

on:
  push:
    branches: [ 'main', '3.x' ]
  pull_request:
    branches: [ 'main', '3.x' ]

permissions: {}

env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always

jobs:

  java:

    name: Java 25 (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'maven'
      - uses: testlens-app/setup-testlens@3f82d2dc6cd5c03f02ce5f7885a21195d85f8d14 # v1.9.3
      - name: Test
        run: ./mvnw $MAVEN_ARGS verify
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@d9f48fc87bc235f7e214acf696ca5abc0a986f16 # v6.4.2
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'

  java-oracle:

    name: Java ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        # https://jdk.java.net/
        java: [26, 27, 28, leyden, loom, valhalla]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Java
        uses: oracle-actions/setup-java@fff43251af9936a0e6a4d5d0946e14f1680e9b6b # v1.5.0
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
          version: latest
      - uses: testlens-app/setup-testlens@3f82d2dc6cd5c03f02ce5f7885a21195d85f8d14 # v1.9.3
      - name: Test
        run: ./mvnw $MAVEN_ARGS verify

  groovy:

    name: Groovy ${{ matrix.groovy }}
    strategy:
      fail-fast: false
      matrix:
        # https://groovy.apache.org/download.html
        groovy: [4.0.32]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'maven'
      - uses: testlens-app/setup-testlens@3f82d2dc6cd5c03f02ce5f7885a21195d85f8d14 # v1.9.3
      - name: Test
        run: ./mvnw $MAVEN_ARGS -pl assertj-tests/assertj-integration-tests/assertj-core-groovy -am -Dgroovy.version=${{ matrix.groovy }} verify

  kotlin:

    name: Kotlin ${{ matrix.kotlin }}
    strategy:
      fail-fast: false
      matrix:
        # https://kotlinlang.org/docs/releases.html#release-details
        kotlin: [2.1.21, 2.2.21]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'maven'
      - uses: testlens-app/setup-testlens@3f82d2dc6cd5c03f02ce5f7885a21195d85f8d14 # v1.9.3
      - name: Test
        run: ./mvnw $MAVEN_ARGS -pl assertj-tests/assertj-integration-tests/assertj-core-kotlin -am -Dkotlin.version=${{ matrix.kotlin }} verify

  javadoc:

    name: Javadoc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'maven'
      - name: Generate Javadoc
        run: ./mvnw $MAVEN_ARGS -DskipTests package javadoc:javadoc
      - name: Upload Javadoc
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: javadoc
          if-no-files-found: error
          path: |
            **/target/reports/apidocs

  sonar:

    name: Sonar code analysis
    runs-on: ubuntu-latest
    if: github.repository_owner == 'assertj' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'maven'
      - uses: testlens-app/setup-testlens@3f82d2dc6cd5c03f02ce5f7885a21195d85f8d14 # v1.9.3
      - name: Test with Sonar
        run: >
          ./mvnw $MAVEN_ARGS verify sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=assertj
          -Dsonar.projectKey=joel-costigliola_assertj-core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish-snapshot:

    name: Publish Snapshot
    needs: [java, javadoc]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'assertj' && github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Maven Central
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'zulu'
          java-version: '25'
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish to Maven Central
        run: ./mvnw $MAVEN_ARGS -DskipTests -Ppublish deploy
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
